#!/usr/bin/env bash
set -xeuo pipefail

systemctl --user start sunshine
sleep 5

gamescopeArgs=(
    --adaptive-sync
    --hdr-enabled
    # --mangoapp
    --rt
    --steam
    # -W 1920
    # -H 1080
    -W 3840
    -H 2160
)
steamArgs=(
    -tenfoot
)
mangoConfig=(
    cpu_temp
    gpu_temp
    ram
    vram
)
mangoVars=(
    MANGOHUD=0
    MANGOHUD_CONFIG="$(IFS=,; echo "${mangoConfig[*]}")"
)

export "${mangoVars[@]}"
exec gamescope "${gamescopeArgs[@]}" -- steam "${steamArgs[@]}"
